const celery = require('celery-node');
const celeryConfig = require('./config');

const client = celery.createClient(
  celeryConfig.BROKER_URL,
  celeryConfig.CELERY_RESULT_BACKEND,
  celeryConfig.QUEUE
);


export const task_trigger = (email) => {
  const task = client.createTask("tasks.mailer");
  const result = task.applyAsync([email]);
  result.get().then(data => {
    console.log('Result generated by worker from subscribe client' + data);
  })
}




