import { NextResponse, NextRequest } from "next/server";
const celery = require('celery-node');
const celeryConfig = require('./config');
import { addSubscriber } from "@/app/lib/subscribe";

export const POST = async (req, res) => {
  const requestBody = await req.text();
  const subscriber = JSON.parse(requestBody);
  console.log(subscriber.email)
  const client = celery.createClient(
    celeryConfig.BROKER_URL,
    celeryConfig.CELERY_RESULT_BACKEND,
    celeryConfig.QUEUE
  );
  const task = client.createTask("tasks.mailer");

  const result = task.applyAsync([subscriber.email]);
  result.get().then(data => {
    console.log('Result generated by worker from client' + data);
    client.disconnect();
  });
  const newSubscriber = addSubscriber(subscriber)
  return NextResponse.json({ message: "Subsriber added", newSubscriber }, { status: 201 })
}
